# Enable long paths for Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android build settings
android.useAndroidX=true
android.enableJetifier=true

# Use only one architecture for faster builds
reactNativeArchitectures=armeabi-v7a

# Increase object path max
CMAKE_OBJECT_PATH_MAX=512
