// Clinic Types for Onboarding
export const CLINIC_TYPES = [
  { value: 'PHYSIOTHERAPY', label: 'Physiotherapy Clinic' },
  { value: 'ORTHOPEDIC', label: 'Orthopedic Clinic' },
  { value: 'MULTISPECIALTY', label: 'Multispecialty Clinic' },
  { value: 'DENTAL', label: 'Dental Clinic' },
  { value: 'GENERAL', label: 'General Clinic' },
  { value: 'DIAGNOSTIC', label: 'Diagnostic Centre' },
  { value: 'PEDIATRIC', label: 'Pediatric Clinic' },
  { value: 'AYURVEDIC', label: 'Ayurvedic Clinic' },
  { value: 'HOMEOPATHIC', label: 'Homeopathic Clinic' },
  { value: 'DERMATOLOGY', label: 'Dermatology Clinic' },
  { value: 'ENT', label: 'ENT Clinic' },
  { value: 'OPHTHALMOLOGY', label: 'Eye Clinic (Ophthalmology)' },
  { value: 'CARDIOLOGY', label: 'Cardiology Clinic' },
  { value: 'GYNECOLOGY', label: 'Gynecology Clinic' },
  { value: 'OTHER', label: 'Other' },
];

// Indian States
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Onboarding Steps Configuration
export const ONBOARDING_STEPS = [
  {
    id: 1,
    key: 'clinic-info',
    title: 'Clinic Information',
    description: 'Clinic name, owner and contact',
    icon: '🏥',
    path: '/clinic/onboarding/step-1',
  },
  {
    id: 2,
    key: 'services',
    title: 'Services & Operations',
    description: 'Services, timings and operations',
    icon: '🩺',
    path: '/clinic/onboarding/step-2',
  },
  {
    id: 3,
    key: 'documents',
    title: 'Clinic Documents',
    description: 'Verify your clinic documents',
    icon: '📄',
    path: '/clinic/onboarding/step-3',
  },
  {
    id: 4,
    key: 'agreement',
    title: 'Partner Agreement',
    description: 'Review and accept agreement',
    icon: '🤝',
    path: '/clinic/onboarding/step-4',
  },
];
